fix: fill config defaults for array of records
Kong/go-kong pull request #302
Opened 2023-03-29 09:14 UTC by nishant95

Add handling for type "record" nested under type "array". 

Currently there is no handling for subconfig of type array, therefore defaults/nil values are not set when there are missing fields in array of records

This fixes the issue by recursively calling the same function for all the records in the array.
Added test for the same

Fixes: #301

2023-03-29 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/go-kong?pullRequest=302) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/go-kong?pullRequest=302) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/go-kong?pullRequest=302) it.</sub>

2023-03-29 18:30 UTC, rainest requested changes
Are you able to add comments that describe the new steps within `fillConfigRecord()`? It's not the simplest bit of code to read, so I think we definitely want comments to help future readers understand it and fix it if needed.

Are you aware of any official Kong plugins whose schema hits this problem? If we can use one of those I'd prefer it over a purpose-built test schema.

2023-03-30 10:08 UTC, nishant95 commented on kong/utils_test.go
> +						"nationality": "African",
> Silly pet peeve, but if we do end up using this, Africa is a continent, not a nation.

Nice catch 😃 
Hadn't given much though to it. Changed it now.

2023-04-03 21:14 UTC, rainest approved these changes
Note: going to handle the changelog separately, will be easier to ping someone here for review than waiting for a change in the fork.

2023-04-03 21:14 UTC, merged

2023-04-03 21:17 UTC, rainest commented
@nishant95 thanks for your contribution! You can claim a contributor T-shirt by following the instructions at https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

2023-04-04 05:11 UTC, nishant95 commented
@rainest I've raised [PR #3843](https://github.com/Kong/kubernetes-ingress-controller/pull/3843) to backport this fix to KIC version 2.6.0, please help with that as well if you can.