chore(*) fix lints
Kong/go-kong pull request #421
Opened 2024-02-26 19:05 UTC by rainest

Blocking dependabot upgrades after a linter upgrade, e.g. https://github.com/Kong/go-kong/actions/runs/8045072066/job/21980638584?pr=420

Discard a bunch of unused parameters and rename a poorly-capitalized argument.

Could probably discard most of the args entirely, but :shrug: they're mostly test objects in test functions, which are kinda standard-ish, so I kept the placeholder around.

2024-03-25 17:10 UTC, flrgh approved these changes

2024-03-29 12:13 UTC, pmalek requested changes

2024-03-29 12:13 UTC, pmalek commented on kong/route_service_test.go
> -		T.Run(tC.name, func(t *testing.T) {
We should use that `t` in assertions below to fail the subtest and not the whole suite

2024-03-29 21:00 UTC, rainest commented
AFAICT https://github.com/Kong/go-kong/commit/241dbb8ae59e27b2a803a02ca19b23ffe64ccb5b includes all of what was originally here.

2024-03-29 21:00 UTC, closed without merging